mainapp/urls.py
from django.urls import path
from . import views



app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),  # /first
    path('home/', views.home, name='home'),
    path('checkme/', views.survey_view, name='checkme'),
    # path('successful/', views.survey_thanks, name='survey_thanks'),

    path('calendar/', views.calendar, name='calendar'),
    path('post/<str:id>', views.post, name='post'),
    # path('new_entry/', views.new_entry, name='new_entry'),

    # path('image_uploads/', views.image_upload, name='image_uploads'),


    path('categories/', views.library_view, name='library_category_list'),
    path('category/<slug:slug>/', views.library_view, name='library_posts_by_category'),

    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),

    # path('lib_user_post/', views.lib_user_post, name='lib_user_post'),

    path('write/', views.daily_post_view, name='daily_post'),  
    path('history/', views.post_history_view, name='post_history'),


]

users/urls.py
from django.urls import path

from . import views
from .views import MyLoginView, UserLogoutView, RegisterView, ResetPasswordView, ChangePasswordView
from django.contrib.auth.views import LogoutView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(http_method_names = ['get', 'post', 'options']), name='logout'),
    path('users_home/', views.users_home, name='users_home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', views.profile, name='users_profile'),



    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_sent.html'),
         name='password_reset_sent'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),


]

websiteProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from users.views import ResetPasswordView, ChangePasswordView
from django.contrib.auth import views as auth_views

# from websiteProject.users.views import ResetPasswordView, ChangePasswordView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('galleryapp/', include('gallery.urls', namespace='gallery')),

    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name = "Назва")
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.name)
            slug = base_slug
            counter = 1
            while Category.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"




class Teg(models.Model):
    name = models.TextField(max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Хештег"
        verbose_name_plural = "Хештеги"




class Post(models.Model):
    title = models.CharField(max_length=30, verbose_name = "Заголовок посту")
    content = models.TextField(verbose_name = "Опис посту")
    published_date = models.DateTimeField(auto_created=True, verbose_name = "Дата та час посту")
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE, verbose_name="Категорія")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name = "Автор")
    poster = models.ImageField(upload_to='uploads')
    teg = models.ManyToManyField(Teg, blank=True, related_name='posts', verbose_name="Хештеги")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "запис юзера в бібл"
        verbose_name_plural = "записи юзера в бібл"


class PersonalPost(models.Model):
    title = models.CharField(max_length=30, verbose_name = "Заголовок посту")
    content = models.TextField(verbose_name = "Опис посту")
    published_date = models.DateTimeField(auto_now_add=True, verbose_name = "Дата та час посту")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name = "Автор")
    poster = models.ImageField(upload_to='uploads' ,verbose_name = "ПостерДоПерсональногоПосту")
    date = models.DateField()

    def __str__(self):
        return f"{self.user.username} - {self.date}"

    class Meta:
        verbose_name = "ОсобистийПост"
        verbose_name_plural = "Особисті Пости"
        unique_together = ('user', 'poster', 'date', 'content')




class LibText(models.Model):
    title = models.CharField(max_length=30, verbose_name="Заголовок мого поля з текстом")
    content = models.TextField(verbose_name="Зміст")
    to_category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Мій текст належить до Категорії")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "пост зАдмінки для Бібліотеки"
        verbose_name_plural = "постИ з адмінки для бібліотеки"



class Survey(models.Model):
    question = models.CharField(max_length=100)

    def __str__(self):
        return self.question





class Answers(models.Model):
    survey = models.ForeignKey(Survey, related_name='answers', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=50)
    def __str__(self):
        return self.choice_text



class UserAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    answer_choice = models.ForeignKey(Answers, on_delete=models.CASCADE)
    answered_at = models.DateTimeField(auto_now_add=True)
    date = models.DateField()

    class Meta:
        unique_together = ('user', 'survey', 'date')  # Унікальна комбінація користувача, опитування і дати

    def __str__(self):
        return f"Відповідь {self.user.username} на {self.survey.question} {self.date}"

mainapp/forms.py
from django import forms

from .models import PersonalPost, Post


# class LibUserPostForm(forms.ModelForm):
#     class Meta:
#         model = LibUserPost
#         exclude = ('published_date', 'user', )
#         widgets = {
#             'content': forms.Textarea(attrs={'rows': 5, 'placeholder': 'Напиши свій пост на сьогодні...'})
#         }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('published_date',  )




class PersonalPostForm(forms.ModelForm):
    class Meta:
        model = PersonalPost
        exclude = ('published_date', 'user', )
        widgets = {
            'content': forms.Textarea(attrs={'rows': 5, 'placeholder': 'Напиши свій пост на сьогодні...'})
        }

mainapp/views.py
from dbm.ndbm import library

from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .forms import PersonalPostForm, PostForm
from django.contrib.auth.decorators import login_required
from .models import Category, Teg, Survey, UserAnswer, Answers, PersonalPost, LibText,  Post
from django.http import HttpResponse

from gallery.models import PhotoGallery


@login_required()
def post(request, id=None):
    post = get_object_or_404(Post, title=id)
    context = {"post": post, }
    # context.update(get_categories(request))
    return  render(request, 'mainapp/post.html', context=context)


def index(request):
    return render(request, 'mainapp/index.html')

@login_required()
def success(request):
    return HttpResponse('successfully uploaded')


@login_required
def survey_view(request):
    surveys = Survey.objects.prefetch_related('answers').all()
    today = timezone.now().date()

    if request.method == 'POST':
        for survey in surveys:
            # Перевіряємо, чи вибрано варіант відповіді для кожного опитування
            selected_answer = request.POST.get(f"survey_{survey.id}")
            if selected_answer:
                # Отримуємо вибраний варіант
                answer_choice = Answers.objects.get(id=selected_answer)
                # Створюємо або оновлюємо відповідь для поточної дати
                UserAnswer.objects.create(
                    user=request.user,
                    survey=survey,
                    answer_choice=answer_choice,
                    date=today  # Зберігаємо поточну дату
                )
                return render(request, 'mainapp/survey_thanks.html')
        # redirect('survey_thanks') # Перенаправляємо користувача на сторінку з підтвердженням
    return render(request, 'mainapp/checkme.html', {'surveys': surveys})






@login_required()
def calendar(request):
    user_answers = UserAnswer.objects.filter(user=request.user)
    user_personal_post = PersonalPost.objects.filter(user=request.user)
    gallery_photo = PhotoGallery.objects.all()
    return render(request, 'mainapp/calendar.html', {'user_answers': user_answers,
                                                     'user_personal_post': user_personal_post,
                                                     'gallery_photo': gallery_photo})




@login_required()
def search(request):
    query = request.GET.get('query', '')
    post_blog_list = Post.objects.filter(Q(content__icontains=query) | Q(title__icontains=query)).order_by("-published_date")
    my_posts_list = LibText.objects.filter(content__icontains=query )
    context = {'post_blog_list': post_blog_list,
               'my_posts_list': my_posts_list,
               'query': query}
    return render(request, 'mainapp/library.html', context=context)



@login_required()
def home(request):
    return render(request, 'mainapp/home.html')


@login_required()
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.published_date = timezone.now()
            post.user = request.user
            post.save()
            form.save_m2m()  # ← для ManyToMany поля "teg"(в тг
            return redirect('mainapp:library_category_list')
    form = PostForm()
    context = {"form": form}
    return render(request, 'mainapp/create.html', context=context)




@login_required()
def category_list_view(request, slug):
    category = get_object_or_404(Category, slug=slug)
    posts = Post.objects.filter(category=category)
    context = {'categories': category, 'posts':posts}
    return render(request, 'mainapp/library.html', context=context)


@login_required()
def posts_by_category_view(request, slug):
    category = get_object_or_404(Category, slug=slug)
    posts = category.posts.all()
    return render(request, 'mainapp/library.html', {'category': category,'posts': posts})


@login_required()
def library_view(request, slug=None):
    categories = Category.objects.all()
    posts = None
    selected_category = None
    if slug:
        selected_category = get_object_or_404(Category, slug=slug)
        posts = selected_category.posts.all()
    return render(request, 'mainapp/library.html', {
        'categories': categories,
        'selected_category': selected_category,
        'posts': posts,
    })




from django.urls import reverse
@login_required
def daily_post_view(request):
    today = timezone.now().date()
    post = PersonalPost.objects.filter(user=request.user, date=today).first()
    if request.method == 'POST':
        # Якщо пост існує, передаємо його в форму, інакше створюємо новий пост
        if post:
            form = PersonalPostForm(request.POST, request.FILES, instance=post)
        else:
            form = PersonalPostForm(request.POST, request.FILES)

        if form.is_valid():
            # Якщо форма валідна, зберігаємо або створюємо новий запис
            post = form.save(commit=False)
            if not post.user_id:
                post.user = request.user  # Призначаємо поточного користувача

            post.save()
            messages.success(request, "Запис успішно збережено!")
            return redirect('mainapp:post_history')  # Або залишити на цій же сторінці
    else:
        # Якщо це не POST-запит, то просто відображаємо форму без створення нових постів
        form = PersonalPostForm(instance=post) if post else PersonalPostForm()
    return render(request, 'mainapp/personal_post.html', {'form': form})


@login_required
def post_history_view(request):
    posts = PersonalPost.objects.filter(user=request.user).order_by('-date')
    return render(request, 'mainapp/personal_post_history.html', {'posts': posts})

templates/mainapp/calendar.html
{% extends 'base.html' %}

{% block content %}

{% load static %}


<h1>календарна таблиця3</h1>

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>
</head>
    <!-- Custom styles for this template -->
<link href="{% static 'mainapp/for_cal.css'%}" rel="stylesheet">
<body>

<p style="background-color:tomato;">Тицни на день та передивись попередньо додані записи та фото з подальшою можливістю зберегти! </p>

<table style="width: 100%;">
<colgroup>
  <col span="2" style="background-color: #D6EEEE">
</colgroup>
<tr>
<th>MON</th>
<th>TUE</th>
<th>WED</th>
<th>THU</th>
<th>FRI</th>
<th>SAT</th>
<th>SUN</th>
</tr>
<tr>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
</tr>
<tr>
<td>8</td>
<td>9</td>
<td>10</td>
<td>11</td>
<td>12</td>
<td>13</td>
<td>14</td>
</tr>
<tr>
<td>15</td>
<td>16</td>
<td>17</td>
<td>18</td>
<td>19</td>
<td>20</td>
<td>21</td>
</tr>
<tr>
<td>22</td>
<td>23</td>
<td>24</td>
<td>25</td>
<td>26</td>
<td>27</td>
<td>28</td>
</tr>
</table>

<button type="button">Отримати статистику !</button>
</body>
</html>


{% for answer in user_answers  %}
    <p>{{ answer.user }}</p>
    <p>{{ answer.survey }}</p>
    <p>{{ answer.answer_choice }}</p>
    <p>{{ answer.answered_at }}</p>
    <p>{{ answer.date }}</p>
    <hr>
{% endfor %}

{% for post in user_personal_post  %}
    <p>{{ post.title }}</p>
    <p>{{ post.content }}</p>
    <p>{{ post.poster }}</p>
    <p>{{ post.published_date }}</p>

    <hr>
{% endfor %}


{% for photo in gallery_photo %}
<img src="{{ photo.image.url }}" alt="{{ photo.description }}" width="500" >

{% endfor %}

{% endblock %}

templates/mainapp/checkme.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<link href="{% static 'mainapp/new_check.css'%}" rel="stylesheet">
<h1>Перевірити свій стан!</h1>
<p style="background-color:tomato;">Опитування</p>


{% for survey in surveys %}
    <h3>{{ survey.question }}</h3>
    <form method="POST">
        {% csrf_token %}
        {% for answer in survey.answers.all %}
            <label>
                <input type="radio" name="survey_{{ survey.id }}" value="{{ answer.id }}">
                {{ answer.choice_text }}
            </label><br>
        {% endfor %}
        <button type="submit">Відправити</button>
    </form>
{% endfor %}



{% endblock %}

templates/mainapp/create.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<link href="{% static 'mainapp/new_check.css'%}" rel="stylesheet">

<!--<p>СТВОРИТИ ЗАПИС В БІБЛІОТЕКУ , ЦІКАВОЇ ІНФОРМАЦІЇ ЯКУ ДЕСЬ ЗНАЙШЛА І ХОЧЕШ СОБІ ЗАФІКСУВАТИ </p>-->
<form action="{% url 'mainapp:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Створити" class="btn btn-default">
</form>
{% endblock %}

templates/mainapp/home.html
{% extends 'base.html' %}



{% block content %}
{% load static %}


<link href="{% static 'mainapp/for_home.css'%}" rel="stylesheet">





{% endblock %}

templates/mainapp/index.html
{% extends 'base.html' %}

{% block content %}


<p>текст для незареєстрованого користувача і більше нічого немає бути </p>
та тут сторінки початкова для користувача який вже зареєстрований, це індекс !
{% endblock %}

templates/mainapp/lib_user_post.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<h2>Створити пост</h2>

<form action="{% url 'mainapp:lib_user_post' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    {% if form.errors %}
        <div style="color: red;">
            <strong>Помилки:</strong>
            <ul>
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
            </ul>
        </div>
    {% endif %}

    <input type="submit" value="Створити">
</form>
{% endblock %}

templates/mainapp/lib_user_post_history.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<h2>Історія твоїх постів бібліотечних</h2>
<ul>
    {% for post in posts %}
        <p>{{ post.title }}</p>

        <img src="{{ post.poster }}" style="max-width: 300px" >
        <p>{{ post.content }}</p>
        <p>{{ post.date }}</p>
    {% empty %}
        <li>Поки що немає постів.</li>
    {% endfor %}
</ul>

{% endblock %}

templates/mainapp/library.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<link href="{% static 'mainapp/for_lib.css'%}" rel="stylesheet">



<hr>
<div class="row">
    <div class="col-nd-4">
        <div class="well">
        <h4>ПОШУК по бібліотеці</h4>
            <form class="input-group" method="GET" action="{% url 'mainapp:search' %}">
                <input class="form-control" type="search" name="query">
                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <span class="glyphicon glyphicon-search">шукати</span>
                                    </button>
                </span>
            </form>
        </div>
    </div>
</div>
<hr>
<hr>
<hr>
<hr>
<hr>
<hr>
<hr>
<h2>Категорії</h2>
<ul>
      {% for category in categories %}
            <li>
              <a href="{% url 'mainapp:library_posts_by_category' slug=category.slug %}">
                {{ category.name }}
              </a>
            </li>
      {% endfor %}
</ul>

<hr>
<hr>
<hr>
<hr>
<hr>
<hr>

{% if selected_category %}
    <p>Пости в категорії(написані користувачем): "{{selected_category.name}}"</p>
        {% if posts %}
            {% for post in posts %}
            <p> class="page-header"><a >{{post.title}} </a></p>
            <p> {{ post.content }} </p>
            <li>{{ post.published_date }} </li>
            <li>{{ post.user }} </li>
            <li><img class="img-responsive" src="{{ post.poster.url }}" alt=""></li>
            {% endfor %}
        {% else %}
            <p>У цій категорії ще немає постів.</p>
        {% endif %}
{% else %}
  <p>Оберіть категорію, щоб побачити пости.</p>
{% endif %}
<hr>
<hr>
<hr>
<hr>

<h2>Результати пошуку по записам користувача :</h2>
{% for post in post_blog_list %}
    <p>{{ post.title }}</p>
    <p>{{ post.content }}</p>
{% empty %}
    <p>Нічого не знайдено !</p>
{% endfor %}

<h2>Результати пошуку по бібліотеці(з адмінпанелі):</h2>
{% for lib in my_posts_list %}
    <p>{{ post.title }}</p>
    <p>{{ lib.content }}</p>
{% empty %}
    <p>Нічого не знайдено !</p>
{% endfor %}

<hr>
<hr>

<p>СТВОРИТИ ЗАПИС В БІБЛІОТЕКУ, ЦІКАВОЇ ІНФОРМАЦІЇ ЯКУ ДЕСЬ ЗНАЙШЛА І ХОЧЕШ СОБІ ЗАФІКСУВАТИ </p>
<form action="{% url 'mainapp:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Створити" class="btn btn-default">
</form>


{% endblock content %}

templates/mainapp/personal_post.html
{% extends 'base.html' %}

{% load static %}
{% block content %}


<hr>
<hr>

<h2>
    {% if form.instance.pk %}
        Ви РЕДАГУЄТЕ існуючий пост на сьогодні.
    {% else %}
        Це твій Новий пост на сьогодні, СТВОРЮЙ :
    {% endif %}
</h2>
<hr>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберегти</button>
</form>
<hr>
<hr>
{% if messages %}
  {% for message in messages %}
    <div>{{ message }}</div>
  {% endfor %}
{% endif %}
<hr>
<hr>
<a href="{% url 'mainapp:post_history' %}">До історії</a>
{% endblock %}

templates/mainapp/personal_post_history.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<h2>Історія твоїх постів</h2>
<ul>
    {% for post in posts %}
        <li><strong>{{ post.date }}</strong>: {{ post.content|linebreaks }}</li>
    {% empty %}
        <li>Поки що немає постів.</li>
    {% endfor %}
</ul>

{% endblock %}

templates/mainapp/post.html
{% extends 'base.html' %}
{% load static %}

<link href="{% static 'mainapp/for_lib.css'%}" rel="stylesheet">

{% block content %}

<hr>
    <h1 class="page-header"><a >{{post.title}} </a></h1>
    <p><a>автор: {{ post.user }}</a>
        {% for teg in tegs %}
            <p><a> {{ teg.name }}</a>
        {% endfor %}
    </p>
    <p>дата поступ: {{ post.published_date }}</p>
    <hr>
    <img class="img-responsive" src="{{post.poster}}" alt="">
    <hr>
    <p> {{ post.content }} </p>


<p>тут сторінка просто посилання на сторінку марштук пост </p>


{% endblock content %}

templates/mainapp/survey_thanks.html
{% extends 'base.html' %}

{% block content %}
 <p>thanks!</p>
{% endblock %}