gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallery'

urlpatterns = [
    path('', views.gallery, name='gallery'), # це на перегляд галереї
    path('uploads/', views.upload, name='uploads')  # це на завантажити шось
]

mainapp/urls.py
from django.urls import path
from . import views



app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),  # /first
    path('home/', views.home, name='home'),
    path('checkme/', views.survey_view, name='checkme'),
    # path('successful/', views.survey_thanks, name='survey_thanks'),

    path('calendar/', views.calendar, name='calendar'),
    path('post/<str:id>', views.post, name='post'),
    # path('new_entry/', views.new_entry, name='new_entry'),

    # path('image_uploads/', views.image_upload, name='image_uploads'),


    path('categories/', views.library_view, name='library_category_list'),
    path('category/<slug:slug>/', views.library_view, name='library_posts_by_category'),

    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),

    # path('lib_user_post/', views.lib_user_post, name='lib_user_post'),

    path('write/', views.daily_post_view, name='daily_post'),  
    path('history/', views.post_history_view, name='post_history'),


]

users/urls.py
from django.urls import path

from . import views
from .views import MyLoginView, UserLogoutView, RegisterView, ResetPasswordView, ChangePasswordView
from django.contrib.auth.views import LogoutView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(http_method_names = ['get', 'post', 'options']), name='logout'),
    path('users_home/', views.users_home, name='users_home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', views.profile, name='users_profile'),



    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_sent.html'),
         name='password_reset_sent'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),


]

websiteProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from users.views import ResetPasswordView, ChangePasswordView
from django.contrib.auth import views as auth_views

# from websiteProject.users.views import ResetPasswordView, ChangePasswordView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('galleryapp/', include('gallery.urls', namespace='gallery')),

    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">


{% load static %}
{% include 'menu.html' %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

<!--     Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">

    <!-- Custom styles for this template -->
<!--  <link href="{% static 'huapp/style.css'%}" rel="stylesheet">-->

  </head>

<body>


    <main role="main" class="container">

      {% block content %}




        {% endblock %}


    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/menu.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-left">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
              aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'mainapp:home' %}">мійКабінет-домашня</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mainapp:calendar' %}">Calendar</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'mainapp:library_category_list' %}">Library</a>
            </li>
             <li class="nav-item">
            <a class="nav-link" href="{% url 'mainapp:checkme' %}">Checkme</a>
             </li>
             <li class="nav-item">
            <a class="nav-link" href="{% url 'gallery:gallery' %}">Gallery</a>
             </li>
             <li class="nav-item">
            <a class="nav-link" href="{% url 'mainapp:daily_post' %}">ЩоденніДумкиЗаписати</a>
             </li>
            {% endif %}
        </ul>
<nav class="nav">

	                {% if request.user.is_authenticated %}


		                	<a href="#">Hi {{ request.user | title }}</a>
	    	                <a href="{% url 'users:logout' %}" class="btn btn-outline">Logout</a>
                            <a href="{% url 'users:users_profile' %}" class="nav-item nav-link">Profile</a>
	                {% else %}
							<a href="{% url 'users:login' %}" class="btn btn-outline">Login</a>
                            <a href="{% url 'users:register' %}" class="btn btn-outline">Sing up</a>

	                {% endif %}
	              </nav>
      </div>
    </nav>